pipeline {
    agent any

    tools {
        nodejs 'NodeJS-20'
    }

    options {
        timestamps()
        skipDefaultCheckout(true)
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('my-react-app') {
                    bat 'npm ci'
                }
            }
        }

        stage('Lint') {
            steps {
                dir('my-react-app') {
                    bat 'npm run lint'
                }
            }
        }

        stage('Build') {
            steps {
                dir('my-react-app') {
                    bat 'npm run build'
                }
            }
        }

        stage('Archive Build') {
            steps {
                archiveArtifacts artifacts: 'my-react-app/dist/**', fingerprint: true
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}